[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kanapy-orix"
version = "6.5.0"
description = "Kanapy with ORIX backend (default)"
authors = [
    { name = "Alexander Hartmaier", email = "alexander.hartmaier@rub.de" },
    { name = "Mahesh R.G. Prasad" },
    { name = "Abhishek Biswas" },
    { name = "Golsa Tolooei Eshlaghi" },
    { name = "Ronak Shoghi" },
    { name = "Napat Vajragupta" },
    { name = "Yousef Rezek" },
    { name = "Hrushikesh Uday Bhimavarapu" }
]
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = [ "LICENSE" ]
requires-python = ">=3.9,<3.13"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
  "kanapy-core>=6.5.0",
  "orix>=0.13",
  "networkx",
  "scikit-image",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["kanapy_orix"]
include-package-data = true
