name: knpy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - pytest-cov
  - packaging
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - matplotlib
  - seaborn
  - click
  - jupyter
