name: knpy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - pytest
  - pytest-mock
  - pytest-cov
  - codecov
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - matplotlib
  - seaborn
  - click
  - cmake
  - jupyter
