package:
  name: kanapy
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  noarch: generic
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: https://github.com/mrgprasad/kanapy
  path: ../src/
  
requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake
    - numpy

  run:
    - python
    - vs2015_runtime  # [win]
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - click
    - tqdm

test:
  imports:
    - kanapy

about:
  summary: A python package for generating complex synthetic polycrystalline microstructures.
  license_file: LICENSE
